// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WebApiKey']!,
    appId: '1:1094348719183:web:6f9dfd1f7935e1ceca163a',
    messagingSenderId: '1094348719183',
    projectId: 'nomadvoyage-2025',
    authDomain: 'nomadvoyage-2025.firebaseapp.com',
    storageBucket: 'nomadvoyage-2025.firebasestorage.app',
    measurementId: 'G-VECCZ4L4D5',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['AndroidApiKey']!,
    appId: '1:1094348719183:android:5ed4aa46f34ed76fca163a',
    messagingSenderId: '1094348719183',
    projectId: 'nomadvoyage-2025',
    storageBucket: 'nomadvoyage-2025.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IosApiKey']!,
    appId: '1:1094348719183:ios:65e2972eb92cba27ca163a',
    messagingSenderId: '1094348719183',
    projectId: 'nomadvoyage-2025',
    storageBucket: 'nomadvoyage-2025.firebasestorage.app',
    iosBundleId: 'com.example.soLink',
  );
}
